---
name: Alt-Acme-Math-XS-EUMM
version: 0.0.1
abstract: 'Math is HARD (faster)'
author:
  - 'Ingy döt Net <ingy@cpan.org>'

build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: Hand
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
no_index:
  directory:
    - lib/Acme
    - inc
    - t
    - xt
    - example
requires:
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/alt-acme-math-xs-eumm-pm/issues
  homepage: https://github.com/ingydotnet/alt-acme-math-xs-eumm-pm
  repository: https://github.com/ingydotnet/alt-acme-math-xs-eumm-pm.git
